name: navi_go
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Version and build number
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  qr_flutter: ^4.0.0
  firebase_auth_web: ^5.13.4
  js: ^0.7.1
  google_maps_flutter: ^2.1.1
  flutter_plugin_android_lifecycle: ^2.0.5
  intl: ^0.17.0
  provider: ^6.0.0
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # Includes the Material Icons font so you can use Material icons
  uses-material-design: true
